# prpl.yaml

# Random seed
seed: 20

# Training session
session: 1

# Number of classes
num_of_class: 3

# Training parameters
batch_size: 96
n_epochs: 1000
early_stop: 100
log_interval: 1

# Optimizer parameters
lr: 1e-3
weight_decay: 1e-5

# Learning rate change parameters
lr_gamma: 0.0003
lr_decay: 0.75
lr_scheduler: false

# Transfer learning related parameters
transfer_loss_weight: 1.0

tmp_saved_path: "E:\\EEG\\logs\\0924\\SC\\"

# # base parameters
# model_type: base
# transfer_loss_type: dann


# Other parameters
num_workers: 0
saved_model: false

